#include "AutoDoor.h"
#include "Components/BoxComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Kismet/GameplayStatics.h"
#include "GameFramework/Character.h"
#include "Engine/World.h"

AAutoDoor::AAutoDoor()
{
    PrimaryActorTick.bCanEverTick = true;

    // ì™¼ìª½ ë¬¸ ì„¤ì •
    LeftDoor = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("LeftDoor"));
    RootComponent = LeftDoor;

    // ì˜¤ë¥¸ìª½ ë¬¸ ì„¤ì •
    RightDoor = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("RightDoor"));
    RightDoor->SetupAttachment(RootComponent);

    // íŠ¸ë¦¬ê±° ë°•ìŠ¤ ì„¤ì •
    TriggerBox = CreateDefaultSubobject<UBoxComponent>(TEXT("TriggerBox"));
    TriggerBox->SetupAttachment(RootComponent);
    TriggerBox->SetCollisionProfileName(TEXT("Trigger"));
    TriggerBox->SetGenerateOverlapEvents(true);

    // ì™¼ìª½ ë¬¸ì€ -Y ë°©í–¥, ì˜¤ë¥¸ìª½ ë¬¸ì€ +Y ë°©í–¥ìœ¼ë¡œ ì´ë™
    LeftDoorOpenOffset = FVector(0, -100, 0);
    RightDoorOpenOffset = FVector(0, 100, 0);
}

void AAutoDoor::BeginPlay()
{
    Super::BeginPlay();

    // ì´ˆê¸° ìœ„ì¹˜ ì €ì¥
    LeftDoorStartPosition = LeftDoor->GetRelativeLocation();
    RightDoorStartPosition = RightDoor->GetRelativeLocation();

    if (TriggerBox)
    {
        TriggerBox->OnComponentBeginOverlap.AddDynamic(this, &AAutoDoor::OnTriggerEnter);
    }

    if (OpenCurve)
    {
        UE_LOG(LogTemp, Warning, TEXT("âœ… OpenCurveê°€ ì •ìƒì ìœ¼ë¡œ ì„¤ì •ë¨!"));

        FOnTimelineFloat ProgressFunction;
        ProgressFunction.BindUFunction(this, FName("MoveDoor"));
        DoorTimeline.AddInterpFloat(OpenCurve, ProgressFunction);
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ OpenCurveê°€ ì„¤ì •ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤!"));
    }
}

void AAutoDoor::OnTriggerEnter(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
    if (OtherActor && OtherActor->IsA(ACharacter::StaticClass()))
    {
        UE_LOG(LogTemp, Warning, TEXT("ğŸšª í”Œë ˆì´ì–´ê°€ íŠ¸ë¦¬ê±° ë°•ìŠ¤ë¥¼ ë°Ÿì•˜ìŠµë‹ˆë‹¤!"));

        if (!DoorTimeline.IsPlaying())
        {
            UE_LOG(LogTemp, Warning, TEXT("ğŸšª ë¬¸ì´ ì—´ë¦¬ëŠ” ì¤‘..."));
            DoorTimeline.PlayFromStart();
        }
    }
}

void AAutoDoor::MoveDoor(float Value)
{
    // ì™¼ìª½ ë¬¸ì€ ì™¼ìª½(-Y)ìœ¼ë¡œ ì´ë™
    FVector NewLeftPosition = FMath::Lerp(LeftDoorStartPosition, LeftDoorStartPosition + LeftDoorOpenOffset, Value);
    LeftDoor->SetRelativeLocation(NewLeftPosition);

    // ì˜¤ë¥¸ìª½ ë¬¸ì€ ì˜¤ë¥¸ìª½(+Y)ìœ¼ë¡œ ì´ë™
    FVector NewRightPosition = FMath::Lerp(RightDoorStartPosition, RightDoorStartPosition + RightDoorOpenOffset, Value);
    RightDoor->SetRelativeLocation(NewRightPosition);

    UE_LOG(LogTemp, Warning, TEXT("ğŸšª ë¬¸ ì´ë™ ê°’: %f"), Value);
}

void AAutoDoor::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
    DoorTimeline.TickTimeline(DeltaTime);
}
